[package]
name = "alterrain-rs"
version = "0.1.0"
authors = ["xuyanwen2012 <info@chivalrystudio.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.0"
actix = "0.9.0"
actix-web = "2.0"
actix-web-actors = "2.0.0"
actix-files = "0.2.1"

env_logger = "0.7.1"